# Generated by Django 4.0.3 on 2022-03-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_horoscopes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='forecast',
            field=models.CharField(max_length=5000),
        ),
    ]
