# Generated by Django 4.0.3 on 2022-03-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_horoscopes', '0003_remove_forecast_forecast_forecast_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='day',
        ),
        migrations.AddField(
            model_name='forecast',
            name='sing',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
